# Array Creation Function

In [1]:
# import numpy 
import numpy as np 

## Generate arrays using `zeros()`
- Returns an array of given shape and type filled with zeros 
- **Syntax:** `np.zeros(shape, dtype)`
    - shape - integer or sequence of integers
    - dtype - data type(default: float)

In [3]:
# 1D array of length 3 with all values 0 
Z1 = np.zeros(10)
print(Z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 2D array of 3x4 with all values 0 
Z2 = np.zeros((3,4))
print(Z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
Z2.shape

(3, 4)

## Generate arrays using `ones()`
- Returns an array of given shape and type filled with ones 
- **Syntax:** `np.ones(shape, dtype)`
    - shape - integer or sequence of integers 
    - dtype - data type(default: float) 

In [9]:
# 1D array of length 3 with all values 1
A1 = np.ones(10)  
print(A1) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


__Note__
- Rows = 3 
- Columns = 4 

In [10]:
# 2D array of 3x4 with all values 1
A2 = np.ones((3,4))
A2
print(A2) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Generate arrays using `arange()`
- Returns equally spaced numbers with in the given range based on step size. 
- **Syntax:** `np.arange(start, stop, step)`
    - start- starts of interval range 
    - stop - end of interval range '
    - step - step size of interval 

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
list(range(1, 20, 2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [ ]:
# not specify start and step 
A1 = np.arange(10)
print(A1)

In [18]:
A = np.arange(1, 10, 2)
A 

array([1, 3, 5, 7, 9])

In [ ]:
# specifying start and step 
A2 = np.arange(start=1, stop=10, step=2)
print(A2)

In [19]:
# another way 
A3 = np.arange(10, 25, 2)
print(A3)

[10 12 14 16 18 20 22 24]


## Generate arrays using `linspace()`
- Returns equally spaced numbers within the given range based on the sample number. 
- **Syntax:**  `np.linspace(start, stop, num, dtype, retstep)`
    - start-start of interval range 
    - stop-end of the interval range 
    - num- number of samples to be generated 
    - dtype-type of output array 
    - retstep-return the samples, step values 

In [21]:
# array of evenly spaced values 0 to 2, here sample size = 9
L1 = np.linspace(0,2,50)
print(L1)

[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]


In [22]:
# Array of 6 evenly divided values from 0 to 100
L2 = np.linspace(0, 100, 6)
print(L2) 

[  0.  20.  40.  60.  80. 100.]


In [27]:
# Array of 1 to 5
L3 = np.linspace(start=1, stop=5, endpoint=True, retstep=False)
print(L3) 

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [26]:
# Array of 1 to 5
L4 = np.linspace(start=1, stop=5, endpoint=True, retstep=True)
print(L4) 

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]), 0.08163265306122448)


__Specifying Endpoint__
- `endpoint=True`, inlcude 5 
- `endpoint=False`,exclude 5 

__Specifying Retstep__
- `retstep=False`, doesn't return the step value
- `endpoint=False`, returns the samples as well step value 

## Generate arrays using `logspace()`
- Returns equally spaced numbers within the given range based on the log scale. 
- **Syntax:**  `np.logspace(start, stop, num, endpoint, base, dtype, retstep)`
    - start- start of the sequence 
    - stop- end of the sequence  
    - num- number of samples to be generated(default: 50)  
    - dtype- type of output array 
    - retstep- return the samples, step values 
    - endpoint - if true, stop is the last sample 
    - base - base of the log space(default: 10.0) 

In [28]:
# generate an array with 5 samples with base 10.0 
np.logspace(1, 10, num=5, endpoint=True)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [29]:
# generate an array with 5 samples with base 2.0
np.logspace(1, 10, num=5, endpoint=True, base=2.0)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

## Generate constant arrays using `full()` 
- Return a new array of given shape and type, filled with `fill_value`. 
- **Syntax:** `np.full(shape,fill_value, dtype)`
    - shape - Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    - fill_value - Fill value(scaler).
    - dtype - The desired data-type for the array

In [30]:
# generate 2x2 constant array, constant = 7
C = np.full((2, 2), 7)
print(C)

[[7 7]
 [7 7]]


## Creating identity matrix using `eye()`
- An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one
- **Syntax:** `np.eye(N, M, k, dtype)`
    - N : Number of rows(int) in the output
    - M : Number of columns in the output. If None, defaults to `N`.
    - k : Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal
    - dtype: Data-type of the returned array.

In [34]:
# generate 2x2 identity matrix 
I = np.eye(2)
print(I) 

[[1. 0.]
 [0. 1.]]


## Generate arrays using random.rand() 
- Returns an array of given shape filled with random values. 
- **Syntax:** `np.random.rand(shape)`
    - shape - integer or sequence of integer 

In [40]:
# create an array with randomly generated 5 values 
R = np.random.rand(5)
print(R)

[0.86280542 0.51915509 0.9383699  0.56039084 0.18475334]


In [41]:
# generate 2x2 array of random values 
R1 = np.random.random((2, 2))
print(R1)

[[0.23436422 0.00496711]
 [0.65064793 0.78261282]]


In [42]:
# generate 4x5 array of random floats between 0-1
R2 = np.random.rand(4,5)
print(R2)

[[0.38552667 0.94144038 0.03092473 0.73364551 0.41224623]
 [0.73734337 0.39744978 0.57429804 0.00833022 0.12073569]
 [0.43394446 0.96606851 0.66450423 0.08561559 0.41158191]
 [0.03512673 0.62793711 0.14370015 0.36719563 0.15808813]]


In [43]:
# generate 6x7 array of random floats between 0-100
R3 = np.random.rand(6,7)*100
print(R3)

[[77.95791755 47.85238371  7.0573093  49.03492727 44.87136896 58.61240869
  11.50669396]
 [15.71740596 56.07912475 12.78846378 39.06553058 24.08871887 82.61439041
  43.86911533]
 [89.97876976 49.22676754 15.61480433  6.22206449 54.82066732  9.2674994
  74.45340615]
 [77.28332628 22.12579019 83.2497566  53.77106543  4.71818875 44.54059954
  93.23605754]
 [35.88276164 77.38256238 56.08488143 45.99710109 11.27947077 39.36421665
  30.26637741]
 [73.08086327 47.00245944 68.44712629 37.26669066  8.92342527 56.97283846
  76.90147286]]


In [48]:
# generate 2x3 array of random ints between 0-4
R4 = np.random.randint(5, size=(2,3))
print(R4)

[[3 3 1]
 [4 3 0]]


## Generate empty arrays using `empty()`
- Return a new array of given shape and type, without initializing entries.
- **Syntax:** `np.empty(shape, dtype)`
    - shape - integer or tuple of integer
    - dtype - data-type


In [ ]:
# generate an empty array 
E1 = np.empty(2) 
print(E1)

In [ ]:
# 2x2 empty array
E2 = np.empty((2, 2)) 
print(E2)

## Arrays using specific data type 
- float16
- float32 
- int8

__SEE MORE__
- https://numpy.org/devdocs/user/basics.types.html

In [ ]:
# generate an array of floats 
D = np.ones((2, 3, 4), dtype=np.float16)
D