# Setting and Slicing Array Elements

In [2]:
import numpy as np 

## Array Slicing

In [4]:
# Create an array 
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(A)

[1 2 3 4 5 6 7 8]


### Positive Indexing
Select `nth` element of an array by using `var[position]`

In [5]:
# Select 0th element of `A`
A[0]

1

In [6]:
# Select 1st element of `A`
A[1]

2

### Negative Indexing

In [7]:
# Select last element of `A`
A[-1]

8

In [8]:
A[-2]

7

Extract a Portion of a Sequence by specifying a lower and upper bound. The lower bound element is `included`, but the upper-bound element is `not included`. Mathematically: [lower, upper]. The stop value specifies the stride between elements.


In [11]:
B = np.array([1, 2, 3, 4, 5, 6, 7])

In [12]:
B 

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# indices: A[i:j] => i: j-1 
B[1:3]

array([2, 3])

In [15]:
# negative indices work also
B[1:-2]

array([2, 3, 4, 5])

In [16]:
B[-4:3]

array([], dtype=int64)

Omitted boundaries are assumed to be the beginning (or end) of the list

In [17]:
# grab first theree elements: first n elements A[: n]
B[:3]

array([1, 2, 3])

In [18]:
B[3:]

array([4, 5, 6, 7])

In [19]:
# grab last two elements 
B[-2:]

array([6, 7])

In [20]:
# grab every other elements 
B[::2]

array([1, 3, 5, 7])

## 2D Array Slicing

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
# grab 1st row and 1st element 
arr[0, 0]

1

In [23]:
# same as above
arr[0, 2]

3

In [24]:
# negative indexing 
arr[0, -1]

3

In [25]:
# select all rows and last element
arr[:, 2]

array([3, 6])